# Generated by Django 3.2.5 on 2021-12-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topsecret',
            old_name='title1',
            new_name='password',
        ),
    ]
