# Generated by Django 3.2.5 on 2021-12-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_title1_topsecret_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsecret',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name=' 🧔 Username'),
        ),
        migrations.AlterField(
            model_name='topsecret',
            name='message',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='💬 Small Message?'),
        ),
        migrations.AlterField(
            model_name='topsecret',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='🔑 Password'),
        ),
        migrations.AlterField(
            model_name='topsecret',
            name='title',
            field=models.CharField(max_length=100, verbose_name=' 🧔 Title / Username'),
        ),
    ]
