# Generated by Django 3.2.5 on 2021-12-09 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211202_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsecret',
            name='key_string',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='key_string '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topsecret',
            name='title',
            field=models.CharField(max_length=100, verbose_name=' 📌 Title '),
        ),
    ]
