# Generated by Django 3.2.5 on 2021-12-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211209_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topsecret',
            name='key_string',
        ),
    ]
